// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMxPn9Gq1sw5Bb7y667fxhNvHhBaY2Y7A',
    appId: '1:303340493351:web:54fca0146f136bc9470c02',
    messagingSenderId: '303340493351',
    projectId: 'bdrs-ac088',
    authDomain: 'bdrs-ac088.firebaseapp.com',
    storageBucket: 'bdrs-ac088.appspot.com', // ✅ corrected to standard Firebase format
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTaojgowT9IND6v8QkK0MFOJXBOhrsWg',
    appId: '1:303340493351:android:18a4350b1671dc12470c02',
    messagingSenderId: '303340493351',
    projectId: 'bdrs-ac088',
    storageBucket: 'bdrs-ac088.appspot.com', // ✅ corrected
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVYHcGKYyawA4mvobBIxZNCUOravVAVjU',
    appId: '1:303340493351:ios:9174c5214044095f470c02',
    messagingSenderId: '303340493351',
    projectId: 'bdrs-ac088',
    storageBucket: 'bdrs-ac088.appspot.com', // ✅ corrected
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVYHcGKYyawA4mvobBIxZNCUOravVAVjU',
    appId: '1:303340493351:ios:9174c5214044095f470c02',
    messagingSenderId: '303340493351',
    projectId: 'bdrs-ac088',
    storageBucket: 'bdrs-ac088.appspot.com', // ✅ corrected
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMxPn9Gq1sw5Bb7y667fxhNvHhBaY2Y7A',
    appId: '1:303340493351:web:15a19c7d007491a7470c02',
    messagingSenderId: '303340493351',
    projectId: 'bdrs-ac088',
    authDomain: 'bdrs-ac088.firebaseapp.com',
    storageBucket: 'bdrs-ac088.appspot.com', // ✅ corrected
  );
}
